# Generated by Django 4.2.7 on 2023-11-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0004_rename_descripcion_equipo_med_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo_med',
            options={'verbose_name': 'Equipo Medico', 'verbose_name_plural': 'Equipos Medicos'},
        ),
    ]
