# Generated by Django 4.2.7 on 2023-12-04 03:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0005_alter_equipo_med_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id',
        ),
        migrations.AddField(
            model_name='empleado',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empleado',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(default='00000000', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='contratacion_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(default='1234', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='phone',
            field=models.CharField(default='0000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='sex',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='surname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='username',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo_med',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('count', models.AutoField(primary_key=True, serialize=False)),
                ('dateentry', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BDMedico.empleado')),
            ],
        ),
    ]
