# Generated by Django 4.2.7 on 2023-12-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0007_rename_empleado_empleados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipo_Med',
        ),
    ]
