# Generated by Django 4.2.7 on 2023-12-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0008_delete_equipo_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='expira',
            field=models.DateField(null=True),
        ),
    ]
