# Generated by Django 5.0 on 2023-12-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0010_alter_empleados_puesto_alter_empleados_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='marca',
            field=models.CharField(default='Generico', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='LOTE',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
