# Generated by Django 5.0 on 2023-12-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0011_medicamento_marca_alter_medicamento_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='marca',
            field=models.CharField(max_length=255),
        ),
    ]
