# Generated by Django 5.0 on 2023-12-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0012_alter_medicamento_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='marca',
            field=models.CharField(default='Generico', max_length=255),
        ),
    ]
