# Generated by Django 5.0 on 2023-12-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0013_alter_medicamento_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
