# Generated by Django 5.0 on 2023-12-06 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0014_alter_empleados_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='contratacion_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
