# Generated by Django 5.0 on 2023-12-06 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0015_alter_empleados_contratacion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='contratacion_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
