# Generated by Django 5.0 on 2023-12-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0016_alter_empleados_contratacion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='contratacion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
