# Generated by Django 5.0 on 2023-12-06 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMedico', '0017_alter_empleados_contratacion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='El número de teléfono solo puede contener números, "+", "-", "#" o "*".', regex='^[0-9+\\-#*]+$')]),
        ),
    ]
